//created on: Apr 13, 2015
package org.acme.insurance.policyquote

import org.acme.insurance.Driver
import org.acme.insurance.Policy
 
rule "RiskyAdults"
	ruleflow-group "calculation"
    when
        //conditions
        driver : Driver(age > 24, numberOfAccidents >= 1 || numberOfTickets >=2)
	policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(300)};
        System.out.println("fired rule " + kcontext.getRule().getName());
 
end

rule "RiskyYouths"
	ruleflow-group "calculation"
    when
        //conditions
        driver : Driver(age >= 18 && < 25, numberOfAccidents >= 1 || numberOfTickets >=2)
	policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(700)};
        System.out.println("fired rule " + kcontext.getRule().getName());
 
end

rule "SafeAdults"
	ruleflow-group "calculation"
    when
        driver : Driver(age > 24, numberOfAccidents < 1, numberOfTickets <= 1)
	policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(120)};
        System.out.println("fired rule " + kcontext.getRule().getName());
 
end

rule "SafeYouths"
	ruleflow-group "calculation"
    when
        driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1)
	    policy : Policy(price == null, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(450)};
        System.out.println("fired rule " + kcontext.getRule().getName());
 
end
